task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from tasks.views import TaskList

urlpatterns = [
    path("", TaskList.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("task/", include("tasks.urls")),
]

tasks/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import (
    TaskList,
    TaskDetailView,
    TaskCreate,
    TaskUpdate,
    TaskDelete,
    TaskViewSet,
    TaskDeleteAPI,
)

router = routers.DefaultRouter()
router.register(r"", TaskViewSet)

urlpatterns = [
    path("", TaskList.as_view(), name="task_list"),
    path("<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path("create/", TaskCreate.as_view(), name="task_create"),
    path("<int:pk>/update/", TaskUpdate.as_view(), name="task_update"),
    path("<int:pk>/delete/", TaskDelete.as_view(), name="task_delete"),
    path("api/ <int:pk>/delete/", TaskDeleteAPI.as_view(), name="task_delete_api"),
    path("api/", include(router.urls)),
]

tasks/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    creation_date = models.DateField(auto_now_add=True)
    due_date = models.DateTimeField()
    priority_choices = [
        ("High", "High"),
        ("Medium", "Medium"),
        ("Low", "Low"),
    ]
    priority = models.CharField(max_length=10, choices=priority_choices, default="Low")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("task_detail", kwargs={"pk": self.pk})

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "description", "due_date", "priority", "complete"]
        widgets = {"due_date": forms.DateTimeInput(attrs={"type": "datetime-local"})}

tasks/views.py
from django.db.models import F
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework import generics, status, viewsets
from rest_framework.response import Response

from .serializers import TaskSerializer
from .models import Task
from .forms import TaskForm


# Create your views here.
class TaskListAPI(generics.ListCreateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class TaskDetailAPI(generics.RetrieveUpdateDestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer


class TaskDeleteAPI(generics.RetrieveUpdateDestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer


class TaskViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer


class TaskList(ListView):
    model = Task
    template_name = "task_list.html"
    context_object_name = "tasks"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["priorities"] = ["High", "Medium", "Low"]
        return context

    def get_queryset(self):
        queryset = Task.objects.all().order_by(F("priority").asc())
        query = self.request.GET.get("q")
        if query:
            queryset = queryset.filter(Q(title__icontains=query))

        creation_date = self.request.GET.get("creation_date")
        if creation_date:
            queryset = queryset.filter(creation_date__date=creation_date)

        due_date = self.request.GET.get("due_date")
        if due_date:
            queryset = queryset.filter(due_date__date=due_date)

        priority = self.request.GET.get("priority")
        if priority:
            queryset = queryset.filter(priority=priority)

        complete = self.request.GET.get("complete")
        if complete == "1":
            queryset = queryset.filter(complete=True)

        elif complete == "0":
            queryset = queryset.filter(complete=False)

        return queryset


class TaskDetailView(DetailView):
    model = Task
    template_name = "task_details.html"
    context_object_name = "task"


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("task_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TaskUpdate(UpdateView):
    model = Task
    template_name = "task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("task_list")


class TaskDelete(DeleteView):
    model = Task
    template_name = "task_delete.html"
    success_url = reverse_lazy("task_list")

tasks/templates/task_delete.html
{% extends 'base.html' %}{% block content %}
    <form method="post">
    {% csrf_token %}
    Are you sure you want to delete "{{ task }}"?</p>
    <input class="btn btn-primary" type="submit" value="Confirm" />
    </form>

{% endblock %}

tasks/templates/task_details.html
{% extends 'base.html' %} {% block content %}

<div class="form-control ">
    <h1>{{ task.title }}</h1>

    <p><strong>Description:</strong> {{ task.description }}</p>

    <p><strong>Created:</strong> {{ task.creation_date }}</p>

    <p><strong>Due:</strong> {{ task.due_date }}</p>

    <p><strong>Priority:</strong> {{ task.get_priority_display }}</p>

    <p>
        <strong>Status:</strong>
        {% if task.is_complete %} Completed {% else %} Incomplete {% endif %}
    </p>

    <a class="btn btn-primary" href="{% url 'task_update' task.pk %}"
        >Edit Task</a
    >

    <br />
    <br />
    <a class="btn btn-danger" href="{% url 'task_delete' task.pk %}"
        >Delete Task</a
    >
</div>

{% endblock %}

tasks/templates/task_form.html
{% extends 'base.html' %}{% block content %}
    <h1 class="text-center">
        {% if form.instance.pk %}Edit{% else %}Create{% endif %} Task
    </h1>

    <form class="form-control" method="post">
        {% csrf_token %}{{ form.as_p }}
        <input class="form-controlbtn btn btn-primary" type="submit" value="Submit"/>
    </form>
{% endblock %}

tasks/templates/task_list.html
{% extends 'base.html' %} {% block content %}

    <div class="text=center">
        <h1>Task List</h1>

    </div>

    <table class="table">
        <thead>
        <tr>
            <th>
                <a href="{% url 'task_create' %}" class="btn btn-primary">Add Task</a>
            </th>
            <th>
                <input type="text" id="search-input" placeholder="Search tasks"/>
            </th>
        </tr>
        </thead>
    </table>

    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Created</th>
            <th>Due Date</th>
            <th>Priority</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>
                    <a href="{% url 'task_detail' task.pk %}">{{ task.title }}</a>
                </td>
                <td>{{ task.creation_date }}</td>
                <td>{{ task.due_date }}</td>
                <td>{{ task.priority }}</td>
                <td>
                    {% if task.complete %}Complete{% else %}Incomplete{% endif %}
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="6">No tasks found.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <title>{% block title %}Home{% endblock %} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"/>
    <style>
        body {
            font-family: 'Poppins', sans-serif;
        }
    </style>
</head>

<body>
<header class="bg-light p-3">
    <div class="container text-center">
        <a class="navbar-brand" href="#"><h1>Task Manager</h1></a>
        <nav class="navbar navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'task_list' %}">Home</a>
                </li>
                {% if user.is_authenticated or user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

<main class="container mt-4">
    {% block content %}{% endblock %}
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
<script>
    const searchInput = document.getElementById("search-input");
    searchInput.addEventListener("keydown", function (event) {
        if (event.key === "Enter") {
            const query = searchInput.value;
            const url =
                window.location.href.split("?")[0] + `?q=${query}`;
            window.location.href = url;
        }
    });
</script>
</body>
</html>